echo Executing NeXTTool to upload /home/ubuntu/NXT/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw...
 /home/ubuntu/NXT/nxtOSEK/bin/fwflash /home/ubuntu/NXT/nxtOSEK/ecrobot/../ecrobot/bios/nxt_bios_rom.rfw
