# Target specific macros
TARGET = BRO_client
TARGET_SOURCES :=        \
    BRO_spam_client.c    \
    common/bt_comm.c  \
    common/simul_config.c
TOPPERS_OSEK_OIL_SOURCE := ./BRO_spam_client.oil

O_PATH ?= build

include /home/ubuntu/NXT/nxtOSEK/ecrobot/ecrobot.mak

